# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd044a4c20ea38a18ca287e21ec57c6429f03fc07ab3ceda63d5b3b2c5958ce7a9e2f046a2d6cbdbaf9debea6f581aa2c90f7b6c95a0cd2fc5ac9497ab9c07d3

test:
  secret_key_base: e320d64979ec3d83e342fd884cae902d9b97253266999028b62aaa6357ef9eaf177782daa0f6e8a476b5ee6a327d725701e81f73b70f02439cdaf36e4399e0d3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: a8357eab6d5280e78db9f32b85c71b5892db4314d8dc86f20824d7c8bcc4be581d065a75af1fe86dde679ae837814a81a18880e1c8aad22c19e0d411cc6e1bf4
